### ISSUE TITLE
UEvent读取的权限问题

### ISSUE THREAD

**Issue by butterl** [RainliFu/UEventObserverApp#1]
Hi ， Thanks for sharing this project！ 

在测试demo的过程中发现Selinux 会拦截netlink的读取, 即使签名成系统应用依旧会被拦截，测试版本Android 10.  除修改系统SElinux 外，还有其他途径么?

```
2021-06-22 20:42:19.479 8740-8740/com.jax.uevent W/com.jax.uevent: Accessing hidden method Landroid/view/View;->computeFitSystemWindows(Landroid/graphics/Rect;Landroid/graphics/Rect;)Z (greylist, reflection, allowed)
2021-06-22 20:42:19.479 8740-8740/com.jax.uevent W/com.jax.uevent: Accessing hidden method Landroid/view/ViewGroup;->makeOptionalFitsSystemWindows()V (greylist, reflection, allowed)
2021-06-22 20:42:20.122 8740-8740/com.jax.uevent W/com.jax.uevent: Accessing hidden method Landroid/os/UEventObserver;->stopObserving()V (greylist, linking, allowed)
2021-06-22 20:42:20.124 8740-8740/com.jax.uevent W/com.jax.uevent: Accessing hidden method Landroid/os/UEventObserver;->startObserving(Ljava/lang/String;)V (greylist, linking, allowed)
2021-06-22 20:42:20.127 8740-8740/com.jax.uevent W/com.jax.uevent: Accessing hidden method Landroid/os/UEventObserver;-><init>()V (greylist, linking, allowed)
2021-06-22 20:42:20.127 8740-8740/com.jax.uevent W/com.jax.uevent: Accessing hidden method Landroid/os/UEventObserver$UEvent;->get(Ljava/lang/String;)Ljava/lang/String; (greylist, linking, allowed)
2021-06-22 20:42:20.551 8740-8740/com.jax.uevent W/UEventObserver: type=1400 audit(0.0:416): avc: denied { create } for scontext=u:r:untrusted_app_27:s0:c157,c256,c512,c768 tcontext=u:r:untrusted_app_27:s0:c157,c256,c512,c768 tclass=netlink_kobject_uevent_socket permissive=0 app=com.jax.uevent
2021-06-22 20:42:20.618 8740-8772/com.jax.uevent E/AndroidRuntime: FATAL EXCEPTION: UEventObserver
    Process: com.jax.uevent, PID: 8740
    java.lang.RuntimeException: Unable to open socket for UEventObserver
        at android.os.UEventObserver.nativeSetup(Native Method)
        at android.os.UEventObserver.access$000(UEventObserver.java:42)
        at android.os.UEventObserver$UEventThread.run(UEventObserver.java:186)
```

**Comment by jaxlifu** [comment]
不好意思，之前一直没留意这个issue，我明天去测试尝试下
